[package]
name = "history-import-old-faithful"
edition.workspace = true
version.workspace = true

[dependencies]
arrow.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
bincode_2.workspace = true
bs58.workspace = true
clap.workspace = true
clickhouse.workspace = true
dashmap.workspace = true
futures-util.workspace = true
log.workspace = true
parquet.workspace = true
serde.workspace = true
serde_with.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
zstd = { workspace = true, features = ["zstdmt"] }
tikv-jemallocator = "0.6"

jetstreamer = { path = ".." }
jetstreamer-firehose.workspace = true
jetstreamer-plugin.workspace = true

solana-account-decoder.workspace = true
solana-address.workspace = true
solana-hash.workspace = true
solana-reward-info.workspace = true
solana-transaction.workspace = true
solana-transaction-error.workspace = true
solana-transaction-status.workspace = true
